services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - 9090:9090
    restart: unless-stopped
    volumes:
      - ./prometheus:/etc/prometheus
      - ./prom_data:/prometheus
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - 3000:3000
    restart: unless-stopped
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=grafana
      - GF_PATHS_PROVISIONING=/usr/share/grafana/conf/provisioning
    volumes:
      #- ./grafana:/etc/grafana/provisioning/datasources
      - ./grafana/provisioning:/usr/share/grafana/conf/provisioning
      #- ./grafana/provisioning/datasources:/usr/share/grafana/conf/provisioning/datasources
  esexporter1:
    image: quay.io/prometheuscommunity/elasticsearch-exporter:latest
    command:
     - '--es.uri=$ES_ENDPOINT1'
     - '--es.indices'
    restart: always
    ports:
    - "9114:9114"
  esexporter2:
    image: quay.io/prometheuscommunity/elasticsearch-exporter:latest
    command:
     - '--es.uri=$ES_ENDPOINT2'
     - '--es.indices'
     - '--web.listen-address=:9115'
    restart: always
    ports:
    - "9115:9115"
volumes:
  prom_data:
