apiVersion: 1
deleteDatasources:
  - name: DS_PROMETHEUS
    orgId: 1

datasources:
  - name: DS_PROMETHEUS
    type: prometheus
    url: http://prometheus:9090
    orgId: 1
    uid: "PBFE396EC0B189D67"
