{
 "title": "Elasticsearch Cluster 13071",
 "description": "Grafana Dashboards for Elasticsearch using Prometheus Datasource. Dashboard for Cluster Stats.",
 "tags": [
  "elasticsearch",
  "es-cluster"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "label_values(elasticsearch_indices_docs,cluster)"
   },
   {
    "name": "instance",
    "label": "Source of metrics",
    "query": "label_values(elasticsearch_indices_docs{cluster=\"$cluster\", name!=\"\"},instance)"
   },
   {
    "name": "name",
    "label": "Node name",
    "query": "label_values(elasticsearch_indices_docs{instance=\"$instance\",cluster=\"$cluster\", name!=\"\"},name)"
   },
   {
    "name": "interval",
    "label": "Rate Interval",
    "query": "5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  { "title": "Cluster Level Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Cluster Health",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "elasticsearch_cluster_health_status{instance=\"$instance\",cluster=\"$cluster\",color=\"red\"}==1 or (elasticsearch_cluster_health_status{instance=\"$instance\",cluster=\"$cluster\",color=\"yellow\"}==1)+2 or\n(elasticsearch_cluster_health_status{instance=\"$instance\",cluster=\"$cluster\",color=\"green\"}==1)+4 "
    }
   ]
  },
  {
   "title": "CPU  Avg.",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg (elasticsearch_process_cpu_percent{instance=\"$instance\",cluster=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Pending Tasks",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 7, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "elasticsearch_cluster_health_number_of_pending_tasks{instance=\"$instance\",cluster=\"$cluster\"}"
    }
   ]
  },
  {
   "title": "Total Indices",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count (elasticsearch_indices_docs_primary{instance=\"$instance\",cluster=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Nodes",
   "type": "stat",
   "description": "Number of nodes in the cluster",
   "gridPos": { "h": 3, "w": 2, "x": 13, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "elasticsearch_cluster_health_number_of_nodes{instance=\"$instance\",cluster=\"$cluster\"}"
    }
   ]
  },
  {
   "title": "Documents",
   "type": "stat",
   "description": "On primary shards",
   "gridPos": { "h": 3, "w": 6, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(elasticsearch_indices_docs_primary{instance=\"$instance\",cluster=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Total Segments",
   "type": "stat",
   "description": "On all nodes\n\n*A segment is a file, aka a lucene index*",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (cluster) (elasticsearch_indices_segment_count_total{instance=~\"$instance\",cluster=~\"$cluster\"})"
    }
   ]
  },
  {
   "title": "JVM Memory Usage",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (elasticsearch_jvm_memory_used_bytes{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"})"
    }
   ]
  },
  {
   "title": "JVM Max Memory",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 4, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (elasticsearch_jvm_memory_pool_max_bytes{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"})"
    }
   ]
  },
  {
   "title": "JVM Memory",
   "type": "stat",
   "description": "% Memory used by selected nodes, both heap and non-heap",
   "gridPos": { "h": 3, "w": 3, "x": 7, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (elasticsearch_jvm_memory_used_bytes{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"}) / sum (elasticsearch_jvm_memory_max_bytes{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"}) * 100"
    }
   ]
  },
  {
   "title": "App Indices",
   "type": "stat",
   "description": "Number of indices not starting with a dot (.)",
   "gridPos": { "h": 3, "w": 3, "x": 10, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count (elasticsearch_indices_docs_primary{instance=\"$instance\",cluster=\"$cluster\",index!~\"\\\\..*\"})"
    }
   ]
  },
  {
   "title": "Data Nodes",
   "type": "stat",
   "description": "Number of data nodes in the cluster",
   "gridPos": { "h": 3, "w": 2, "x": 13, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "elasticsearch_cluster_health_number_of_data_nodes{instance=\"$instance\",cluster=\"$cluster\"}"
    }
   ]
  },
  {
   "title": "Data",
   "type": "stat",
   "description": "On all shards",
   "gridPos": { "h": 3, "w": 6, "x": 15, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(elasticsearch_indices_store_size_bytes_total{instance=\"$instance\",cluster=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Primary Segments",
   "type": "stat",
   "description": "On primary shards\n\n*A segment is a file, aka a lucene index*",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (cluster) (elasticsearch_indices_segment_count_primary{instance=~\"$instance\",cluster=~\"$cluster\"})"
    }
   ]
  },
  { "title": "Shards", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Total Shards",
   "type": "stat",
   "description": "All shards, both primary and replica shards",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "elasticsearch_cluster_health_active_shards{instance=\"$instance\",cluster=\"$cluster\"}"
    }
   ]
  },
  {
   "title": "Primary Shards",
   "type": "stat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 11 },
   "repeat": "shard_type",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "elasticsearch_cluster_health_active_primary_shards{instance=\"$instance\",cluster=\"$cluster\"}"
    }
   ]
  },
  {
   "title": "Initializing Shards",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "elasticsearch_cluster_health_initializing_shards{instance=\"$instance\",cluster=\"$cluster\"}"
    }
   ]
  },
  {
   "title": "Relocating Shards",
   "type": "stat",
   "description": "Number of shards which are relocating to another node",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "elasticsearch_cluster_health_relocating_shards{instance=\"$instance\",cluster=\"$cluster\"}"
    }
   ]
  },
  {
   "title": "Delayed Shards",
   "type": "stat",
   "description": "Number of shards which are delayed relocating to another node",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "elasticsearch_cluster_health_delayed_unassigned_shards{instance=\"$instance\",cluster=\"$cluster\"} "
    }
   ]
  },
  {
   "title": "Unassigned Shards",
   "type": "stat",
   "description": "Number of shards that exist in the cluster state, but cannot be found in the cluster itself",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "elasticsearch_cluster_health_unassigned_shards{instance=\"$instance\",cluster=\"$cluster\"} "
    }
   ]
  },
  { "title": "Nodes & Indices", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Nodes Status",
   "type": "table-old",
   "description": "Current status of all nodes in cluster\n\n###### Notes\n\n+ `Blue`: constant value\n+ `Fds`: File Descriptors\n+ `Throttle`: flag `is_throttled`\n",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "sum by (name) (elasticsearch_os_cpu_percent{instance=~\"$instance\",cluster=\"$cluster\"})",
     "legendFormat": "CPU Usage"
    },
    {
     "expr": "sum by (name) (elasticsearch_os_load5{instance=~\"$instance\",cluster=\"$cluster\"})",
     "legendFormat": "Load Average"
    },
    {
     "expr": "sum by (name) (elasticsearch_jvm_memory_used_bytes{instance=~\"$instance\",cluster=\"$cluster\"}) / sum by (name) (elasticsearch_jvm_memory_max_bytes{instance=~\"$instance\",cluster=\"$cluster\"}) * 100",
     "legendFormat": "JVM Memory"
    },
    {
     "expr": "sum by (name) (elasticsearch_filesystem_data_available_bytes{instance=~\"$instance\",cluster=\"$cluster\"})",
     "legendFormat": "Disk Free Space"
    },
    {
     "expr": "sum by (name) (elasticsearch_nodes_roles{instance=~\"$instance\",cluster=\"$cluster\",role=\"master\"})",
     "legendFormat": "Master Node"
    },
    {
     "expr": "sum by (name) (elasticsearch_nodes_roles{instance=~\"$instance\",cluster=\"$cluster\",role=\"data\"})",
     "legendFormat": "Data Node"
    },
    {
     "expr": "sum by (name) (elasticsearch_nodes_roles{instance=~\"$instance\",cluster=\"$cluster\",role=\"ingest\"})",
     "legendFormat": "Ingest Node"
    },
    {
     "expr": "sum by (name) (elasticsearch_nodes_roles{instance=~\"$instance\",cluster=\"$cluster\",role=\"client\"})",
     "legendFormat": "Client Node"
    },
    {
     "expr": "1 - sum by (name) (elasticsearch_filesystem_data_available_bytes{instance=~\"$instance\",cluster=\"$cluster\"}) / sum by (name) (elasticsearch_filesystem_data_size_bytes{instance=~\"$instance\",cluster=\"$cluster\"})",
     "legendFormat": "% Disk Used"
    },
    {
     "expr": "sum by (name) (elasticsearch_indices_store_size_bytes{instance=~\"$instance\",cluster=\"$cluster\"})",
     "legendFormat": "Index Store Data"
    },
    {
     "expr": "sum by (name) (elasticsearch_indices_segments_memory_bytes{instance=~\"$instance\",cluster=\"$cluster\"})",
     "legendFormat": "Segment Memory"
    },
    {
     "expr": "sum by (name) (elasticsearch_indices_segments_count{instance=~\"$instance\",cluster=\"$cluster\"})",
     "legendFormat": "Segment Count"
    },
    {
     "expr": "sum by (name) (elasticsearch_process_open_files_count{instance=~\"$instance\",cluster=\"$cluster\"})",
     "legendFormat": "Open Fds"
    },
    {
     "expr": "sum by (name) (elasticsearch_process_max_files_descriptors{instance=~\"$instance\",cluster=\"$cluster\"})",
     "legendFormat": "Max Fds"
    },
    {
     "expr": "sum by (name) (elasticsearch_indices_indexing_is_throttled{instance=~\"$instance\",cluster=\"$cluster\"})",
     "legendFormat": "Throttle"
    }
   ]
  },
  {
   "title": "Indices Status on Primary Shards",
   "type": "table-old",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "sum by (index) (elasticsearch_indices_docs_primary{instance=~\"$instance\",cluster=\"$cluster\"})",
     "legendFormat": "A"
    },
    {
     "expr": "sum by (index) (elasticsearch_indices_deleted_docs_primary{instance=~\"$instance\",cluster=\"$cluster\"})",
     "legendFormat": "B"
    },
    {
     "expr": "sum by (index) (elasticsearch_indices_store_size_bytes_primary{instance=~\"$instance\",cluster=\"$cluster\"})",
     "legendFormat": "C"
    },
    {
     "expr": "sum by (index) (elasticsearch_indices_segment_memory_bytes_primary{instance=~\"$instance\",cluster=\"$cluster\"})",
     "legendFormat": "D"
    },
    {
     "expr": "sum by (index) (elasticsearch_indices_segment_count_primary{instance=~\"$instance\",cluster=\"$cluster\"})",
     "legendFormat": "E"
    },
    {
     "expr": "count by (index) (elasticsearch_indices_shared_docs{instance=~\"$instance\",cluster=\"$cluster\"})",
     "legendFormat": "F"
    }
   ]
  },
  {
   "title": "Cluster Indexing - $cluster",
   "type": "timeseries",
   "description": "Indexing rate on cluster\n\n`ProcRate`: processing ability, which is the number of requests that Elasticsearch can handle. Estimation is based on the processed requests and processed time for these requests.\n",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum (rate(elasticsearch_indices_indexing_index_total{instance=~\"$instance\",cluster=\"$cluster\"}[$interval]))",
     "legendFormat": "ReqRate"
    },
    {
     "expr": "1 / (\nsum (rate(elasticsearch_indices_indexing_index_time_seconds_total{instance=~\"$instance\",cluster=\"$cluster\"}[$interval])) / \nsum (rate(elasticsearch_indices_indexing_index_total{instance=~\"$instance\",cluster=\"$cluster\"}[$interval]))\n)",
     "legendFormat": "ProcRate"
    }
   ]
  },
  {
   "title": "Cluster Search - $cluster",
   "type": "timeseries",
   "description": "Searching rate on cluster\n\n`ProcRate`: processing ability, which is the number of requests that Elasticsearch can handle. Estimation is based on the processed requests and processed time for those requests.\n",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum (rate(elasticsearch_indices_search_query_total{instance=~\"$instance\",cluster=\"$cluster\"}[$interval]))",
     "legendFormat": "ReqRate"
    },
    {
     "expr": "1 / (\n(sum(rate(elasticsearch_indices_search_query_time_seconds{instance=~\"$instance\",cluster=\"$cluster\"}[$interval]))\n+ sum(rate(elasticsearch_indices_search_fetch_time_seconds{instance=~\"$instance\",cluster=\"$cluster\"}[$interval]))\n+ sum(rate(elasticsearch_indices_search_scroll_time_seconds{instance=~\"$instance\",cluster=\"$cluster\"}[$interval]))\n+ sum(rate(elasticsearch_indices_search_suggest_time_seconds{instance=~\"$instance\",cluster=\"$cluster\"}[$interval]))\n) /\nsum(rate(elasticsearch_indices_search_query_total{instance=~\"$instance\",cluster=\"$cluster\"}[$interval]))\n)",
     "legendFormat": "ProcRate"
    }
   ]
  },
  {
   "title": "Indexing ReqRate (req/s)",
   "type": "timeseries",
   "description": "Indexing rate on data nodes",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(elasticsearch_indices_indexing_index_total{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\",es_data_node=\"true\"}[$interval])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Search Query ReqRate (req/s)",
   "type": "timeseries",
   "description": "Search query rate on data nodes",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(elasticsearch_indices_search_query_total{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\",es_data_node=\"true\"}[$interval])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Times Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 },
   "collapsed": true,
   "panels": [
    {
     "title": "Search Query Time",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 44 },
     "targets": [
      {
       "expr": "rate(elasticsearch_indices_search_query_time_seconds{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"}[$interval]) ",
       "legendFormat": "{{name}}"
      },
      {
       "expr": "sum(rate(elasticsearch_indices_search_query_time_seconds{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"}[$interval]))",
       "legendFormat": "All"
      }
     ]
    },
    {
     "title": "Indexing Time",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 44 },
     "targets": [
      {
       "expr": "rate(elasticsearch_indices_indexing_index_time_seconds_total{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"}[$interval])",
       "legendFormat": "{{name}}"
      },
      {
       "expr": "sum(rate(elasticsearch_indices_indexing_index_time_seconds_total{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"}[$interval]))",
       "legendFormat": "All"
      }
     ]
    },
    {
     "title": "Merging Time",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 44 },
     "targets": [
      {
       "expr": "rate(elasticsearch_indices_merges_total_time_seconds_total{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"}[$interval])",
       "legendFormat": "{{name}}"
      },
      {
       "expr": "sum(rate(elasticsearch_indices_merges_total_time_seconds_total{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"}[$interval]))",
       "legendFormat": "All"
      }
     ]
    },
    {
     "title": "Refresh Time",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 51 },
     "targets": [
      {
       "expr": "rate(elasticsearch_indices_refresh_time_seconds_total{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"}[$interval])",
       "legendFormat": "{{name}}"
      },
      {
       "expr": "sum(rate(elasticsearch_indices_refresh_time_seconds_total{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"}[$interval]))",
       "legendFormat": "All"
      }
     ]
    },
    {
     "title": "Throttle Time for Index Store",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 51 },
     "targets": [
      {
       "expr": "rate(elasticsearch_indices_store_throttle_time_seconds_total{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"}[$interval])",
       "legendFormat": "{{name}}"
      },
      {
       "expr": "sum(rate(elasticsearch_indices_store_throttle_time_seconds_total{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"}[$interval]))",
       "legendFormat": "All"
      }
     ]
    }
   ]
  },
  {
   "title": "Documents by Node",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 },
   "collapsed": true,
   "panels": [
    {
     "title": "Documents Count",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 45 },
     "targets": [
      {
       "expr": "elasticsearch_indices_docs{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"}",
       "legendFormat": "{{name}}"
      },
      {
       "expr": "sum(elasticsearch_indices_docs{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"})",
       "legendFormat": "All"
      }
     ]
    },
    {
     "title": "Merged Documents / s",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 45 },
     "targets": [
      {
       "expr": "rate(elasticsearch_indices_merges_docs_total{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"}[$interval])",
       "legendFormat": "{{name}}"
      },
      {
       "expr": "sum(rate(elasticsearch_indices_merges_docs_total{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"}[$interval]))",
       "legendFormat": "All"
      }
     ]
    },
    {
     "title": "Deleted Documents",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 45 },
     "targets": [
      {
       "expr": "elasticsearch_indices_docs_deleted{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"}",
       "legendFormat": "{{name}}"
      },
      {
       "expr": "sum(elasticsearch_indices_docs_deleted{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"})",
       "legendFormat": "All"
      }
     ]
    },
    {
     "title": "Documents Index Rate",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 51 },
     "targets": [
      {
       "expr": "rate(elasticsearch_indices_indexing_index_total{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"}[$interval])",
       "legendFormat": "{{name}}"
      },
      {
       "expr": "sum(rate(elasticsearch_indices_indexing_index_total{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"}[$interval]))",
       "legendFormat": "All"
      }
     ]
    },
    {
     "title": "Merged Bytes / s",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 51 },
     "targets": [
      {
       "expr": "rate(elasticsearch_indices_merges_total_size_bytes_total{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"}[$interval])",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Documents Deleted Rate",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 51 },
     "targets": [
      {
       "expr": "rate(elasticsearch_indices_docs_deleted{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"}[$interval])",
       "legendFormat": "{{name}}"
      },
      {
       "expr": "sum(rate(elasticsearch_indices_docs_deleted{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"}[$interval]))",
       "legendFormat": "All"
      }
     ]
    }
   ]
  },
  {
   "title": "Thread Pool by Node",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 },
   "collapsed": true,
   "panels": [
    {
     "title": "Thread Pool operations queued",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 46 },
     "targets": [
      {
       "expr": "sum by (name) (elasticsearch_thread_pool_queue_count{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"})",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Thread Pool operations completed",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 46 },
     "targets": [
      {
       "expr": "sum by (name) (elasticsearch_thread_pool_completed_count{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"})",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Thread Pool operations rejected",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 46 },
     "targets": [
      {
       "expr": "sum by (name) (elasticsearch_thread_pool_rejected_count{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"})",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Thread Pool threads active",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 52 },
     "targets": [
      {
       "expr": "sum by (name) (elasticsearch_thread_pool_active_count{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"})",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Thread Pool current threads count",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 52 },
     "targets": [
      {
       "expr": "sum by (name) (elasticsearch_thread_pool_threads_count{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"})",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Thread Pool largest threads count",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 52 },
     "targets": [
      {
       "expr": "sum by (name) (elasticsearch_thread_pool_largest_count{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"})",
       "legendFormat": "{{name}}"
      }
     ]
    }
   ]
  },
  { "title": "JVM Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 } },
  {
   "title": "JVM Memory Usage - $name",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 53 },
   "repeat": "name",
   "targets": [
    {
     "expr": "elasticsearch_jvm_memory_max_bytes{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\",area=\"heap\"}",
     "legendFormat": "Max heap"
    },
    {
     "expr": "elasticsearch_jvm_memory_used_bytes{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\",area=\"heap\"}",
     "legendFormat": "Used heap"
    },
    {
     "expr": "elasticsearch_jvm_memory_used_bytes{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\",area=\"non-heap\"}",
     "legendFormat": "Non-Heap"
    },
    {
     "expr": "elasticsearch_jvm_memory_used_bytes{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\",area=\"heap\"} / elasticsearch_jvm_memory_max_bytes{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\",area=\"heap\"} * 100",
     "legendFormat": "% Used Heap"
    }
   ]
  },
  { "title": "Disk and Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 88 } },
  {
   "title": "Disk usage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 89 },
   "targets": [
    {
     "expr": "(1-\n(elasticsearch_filesystem_data_available_bytes{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"} /\nelasticsearch_filesystem_data_size_bytes{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"})\n)*100",
     "legendFormat": "{{name}}: {{path}}"
    }
   ]
  },
  {
   "title": "Network",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 89 },
   "targets": [
    {
     "expr": "irate(elasticsearch_transport_tx_size_bytes_total{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"}[$interval])",
     "legendFormat": "{{name}}: sent"
    },
    {
     "expr": "irate(elasticsearch_transport_rx_size_bytes_total{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"}[$interval])",
     "legendFormat": "{{name}}: received"
    }
   ]
  },
  {
   "title": "Disk Read/Write",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 99 },
   "targets": [
    {
     "expr": "irate(elasticsearch_filesystem_io_stats_device_read_size_kilobytes_sum{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"}[$interval])",
     "legendFormat": "{{name}}: read"
    },
    {
     "expr": "irate(elasticsearch_filesystem_io_stats_device_write_size_kilobytes_sum{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"}[$interval])",
     "legendFormat": "{{name}}: write"
    }
   ]
  },
  {
   "title": "Disk Read/Write Count",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 99 },
   "targets": [
    {
     "expr": "irate(elasticsearch_filesystem_io_stats_device_read_operations_count{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"}[$interval])",
     "legendFormat": "{{name}}: read"
    },
    {
     "expr": "irate(elasticsearch_filesystem_io_stats_device_write_operations_count{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"}[$interval])",
     "legendFormat": "{{name}}: write"
    }
   ]
  },
  {
   "title": "Open File Descriptors",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 109 },
   "targets": [
    {
     "expr": "elasticsearch_process_open_files_count{instance=\"$instance\",cluster=\"$cluster\"}",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Segments on Nodes",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 109 },
   "targets": [
    {
     "expr": "elasticsearch_indices_segments_count{instance=\"$instance\",cluster=\"$cluster\"}",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "JVM Garbage Collection",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 119 },
   "collapsed": true,
   "panels": [
    {
     "title": "JVM GC Runs / s ",
     "type": "timeseries",
     "description": "Number of JVM GC runs in second by nodes.\nThreshold is 1 GC/s",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 93 },
     "targets": [
      {
       "expr": "rate(elasticsearch_jvm_gc_collection_seconds_count{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"}[$interval])",
       "legendFormat": "{{name}} - {{gc}}"
      }
     ]
    },
    {
     "title": "JVM GC Runtime / s ",
     "type": "timeseries",
     "description": "JVM GC runtime in second by nodes\nThreshold is 40ms / s",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 93 },
     "targets": [
      {
       "expr": "rate(elasticsearch_jvm_gc_collection_seconds_sum{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"}[5m]) * 1000",
       "legendFormat": "{{name}} - {{gc}}"
      }
     ]
    }
   ]
  },
  {
   "title": "File Descriptors",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 120 },
   "collapsed": true,
   "panels": [
    {
     "title": "File Descriptors - $name",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 94 },
     "repeat": "name",
     "targets": [
      {
       "expr": "elasticsearch_process_open_files_count{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"}",
       "legendFormat": "Open Fds"
      },
      {
       "expr": "elasticsearch_process_max_files_descriptors{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"}",
       "legendFormat": "Max Fds"
      },
      {
       "expr": "elasticsearch_process_open_files_count{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"} / elasticsearch_process_max_files_descriptors{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"} * 100",
       "legendFormat": "% Open Fds"
      }
     ]
    }
   ]
  },
  {
   "title": "Transaction Log by Node",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 121 },
   "collapsed": true,
   "panels": [
    {
     "title": "Translog operations / s",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 95 },
     "targets": [
      {
       "expr": "irate(elasticsearch_indices_translog_operations{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"}[$interval])",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Total Translog Operations",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 95 },
     "targets": [
      {
       "expr": "elasticsearch_indices_translog_operations{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"}",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Total Translog Size",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 95 },
     "targets": [
      {
       "expr": "irate(elasticsearch_indices_translog_size_in_bytes{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"}[$interval])",
       "legendFormat": "{{name}}"
      }
     ]
    }
   ]
  },
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 122 } },
  {
   "title": "OS Load Average",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 123 },
   "targets": [
    {
     "expr": "elasticsearch_os_load1{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "OS CPU Usage",
   "type": "timeseries",
   "description": "% CPU used by OS",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 123 },
   "targets": [
    {
     "expr": "elasticsearch_os_cpu_percent{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Process CPU Usage",
   "type": "timeseries",
   "description": "% CPU used by process",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 123 },
   "targets": [
    {
     "expr": "elasticsearch_process_cpu_percent{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Index Memory - $name",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 130 },
   "repeat": "name",
   "collapsed": true,
   "panels": [
    {
     "title": "Index Memory - Lucene - $name",
     "type": "timeseries",
     "description": "+ *Lucene Total*: Total heap memory used by Lucene for current index. This is the sum of other fields for primary and replica shards on this node.\n\n+ *Stored Fields*: Heap memory used by Stored Fields (e.g., _source). This is a part of Lucene Total.. \n\n+ *Doc Values*: Heap memory used by Doc Values. This is a part of Lucene Total.. \n\n+ *Norms*: Heap memory used by Norms (normalization factors for query-time, text scoring). This is a part of Lucene Total.\n\n+ *Terms*: (e.g., text). This is a part of Lucene Total.\n\n+ *Points*: Heap memory used by Points (e.g., numbers, IPs, and geo data). This is a part of Lucene Total.\n\n+ *Fixed Bitsets*: (e.g., text). This is a part of Lucene Total.\n\n+ *Term Vectors*: Heap memory used by Term Vectors. This is a part of Lucene Total.\n\n+ *Version Map*: Heap memory used by Versioning (e.g., updates and deletes). This is NOT a part of Lucene Total.",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 104 },
     "targets": [
      {
       "expr": "elasticsearch_indices_segments_stored_fields_memory_in_bytes{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"}",
       "legendFormat": "Stored Fields"
      },
      {
       "expr": "elasticsearch_indices_segments_doc_values_memory_in_bytes{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"}",
       "legendFormat": "Doc Values"
      },
      {
       "expr": "elasticsearch_indices_segments_norms_memory_in_bytes{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"}",
       "legendFormat": "Norms"
      },
      {
       "expr": "elasticsearch_indices_segments_fixed_bit_set_memory_in_bytes{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"}",
       "legendFormat": "Fixed Bitsets"
      },
      {
       "expr": "elasticsearch_indices_segments_term_vectors_memory_in_bytes{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"}",
       "legendFormat": "Term Vectors"
      },
      {
       "expr": "elasticsearch_indices_segments_version_map_memory_in_bytes{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"}",
       "legendFormat": "Version Map"
      },
      {
       "expr": "elasticsearch_indices_segments_terms_memory_in_bytes{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"}",
       "legendFormat": "Terms"
      },
      {
       "expr": "elasticsearch_indices_segments_points_memory_in_bytes{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"}",
       "legendFormat": "Points"
      },
      {
       "expr": "elasticsearch_indices_segments_memory_bytes{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"}",
       "legendFormat": "Lucene Total"
      }
     ]
    },
    {
     "title": "Index Memory - Elasticsearch - $name",
     "type": "timeseries",
     "description": "+ *Query Cache*: Heap memory used by Query Cache (e.g., cached filters). This is for the same shards, but not a part of Lucene Total.. \n\n+ *Request Cache*: Heap memory used by Request Cache (e.g., instant aggregations). This is for the same shards, but not a part of Lucene Total.. \n\n+ *Fielddata*: Heap memory used by Fielddata (e.g., global ordinals or explicitly enabled fielddata on text fields). This is for the same shards, but not a part of Lucene Total.. \n\n+ *Index Writer*: Heap memory used by the Index Writer. This is NOT a part of Lucene Total.",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 112 },
     "targets": [
      {
       "expr": "elasticsearch_indices_query_cache_memory_size_bytes{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"}",
       "legendFormat": "Query Cache"
      },
      {
       "expr": "elasticsearch_indices_request_cache_memory_size_bytes{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"}",
       "legendFormat": "Request Cache"
      },
      {
       "expr": "elasticsearch_indices_fielddata_memory_size_bytes{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"}",
       "legendFormat": "Fielddata"
      },
      {
       "expr": "elasticsearch_indices_segments_index_writer_memory_in_bytes{instance=\"$instance\",cluster=\"$cluster\",name=~\"$name\"}",
       "legendFormat": "Index Writer"
      }
     ]
    }
   ]
  },
  {
   "title": "Misc",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 145 },
   "collapsed": true,
   "panels": [
    {
     "title": "Shards Changes",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 318 },
     "targets": [
      {
       "expr": "elasticsearch_cluster_health_relocating_shards{instance=\"$instance\",cluster=\"$cluster\"}",
       "legendFormat": "relocating"
      },
      {
       "expr": "elasticsearch_cluster_health_active_primary_shards{instance=\"$instance\",cluster=\"$cluster\"}",
       "legendFormat": "active primary"
      },
      {
       "expr": "elasticsearch_cluster_health_active_shards{instance=\"$instance\",cluster=\"$cluster\"}",
       "legendFormat": "active"
      },
      {
       "expr": "elasticsearch_cluster_health_initializing_shards{instance=\"$instance\",cluster=\"$cluster\"}",
       "legendFormat": "initializing"
      },
      {
       "expr": "elasticsearch_cluster_health_unassigned_shards{instance=\"$instance\",cluster=\"$cluster\"}",
       "legendFormat": "unassigned"
      },
      {
       "expr": "elasticsearch_cluster_health_delayed_unassigned_shards{instance=\"$instance\",cluster=\"$cluster\"}",
       "legendFormat": "unassigned"
      }
     ]
    },
    {
     "title": "Segments Changes",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 318 },
     "targets": [
      {
       "expr": "sum by (cluster) (elasticsearch_indices_segment_count_total{instance=~\"$instance\",cluster=~\"$cluster\"})",
       "legendFormat": "segments"
      }
     ]
    },
    {
     "title": "Total Scrapes",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 318 },
     "targets": [
      {
       "expr": "elasticsearch_cluster_health_total_scrapes{instance=\"$instance\"}",
       "legendFormat": "Scrapes"
      }
     ]
    }
   ]
  }
 ]
}